# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: GenerateLivingSpec
      run: |
        [ "${{ inputs.test-assembly-path }}" != 'null' ] && _path="${{ inputs.test-assembly-path }}"
        _dll="${_path:+$_path/}${{ inputs.test-assembly-dll }}"
        _test="${_path:+$_path/}${{ inputs.test-execution-json }}"
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        livingdoc test-assembly "$_dll" -t "$_test" -o "${{ inputs.output-html }}"
    - name: 'Publish Specflow Test Results'
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: 'Specflow Test Results'
        path: ${{ inputs.output-html }}
    - name: ReturnCode
      run: |
        exit "${_EXIT:-0}"
